Feat/ticket storer
vimond/actions pull request #11
Opened 2022-08-03 09:18 UTC by erlend-vimond

## *What* does this PR do?
- Adds ticket-storer and ticket-storer-pr actions.
  - Ticket-storer is triggered on each push and stores the related tickets in DynamoDB
  - Ticket-storer-pr stores the tickets related to a PR whenever it is opened, changed, closed etc.

## *Why* are you suggesting this change?
This is the start of the compliance workflow.

## *Who* is the change affecting?
Everyone using the GH actions workflow, currently noone.

## *What* is affected by this change?
The vimond-central workflow.
 
## JIRA Tickets
PLAT-564

## Dependencies
None

## Known risks
We are putting (very limited) AWS creds in GH secrets.

## Automated Testing
None

## Manual Testing
Seems to work fine for the testing-terraform-management project: https://github.com/vimond/testing-terraform-management/runs/7648570541?check_suite_focus=true

2022-08-03 18:22 UTC, dagvl requested changes
Mostly style and minor stuff. Only major thing is that we should refactor out shared code so it is clear that it is shared.

2022-08-03 18:22 UTC, dagvl commented on ticket-storer-pr/src/dynamodb.js
> +            "ID": { S: `PR:${prID}` },
style: Mixing string concatenation and string templating

2022-08-03 18:22 UTC, dagvl commented on ticket-storer/index.js
> +      allTickets = allTickets.concat([...tickets]);
I think idiomatic js would be:
```
allTickets = allTickets.concat(...tickets);
```
example:
```
> a = Array(1,2)
[ 1, 2 ]
> b = new Set()
Set(0) {}
> b.add(3)
Set(1) { 3 }
> b.add(4)
Set(2) { 3, 4 }
> a
[ 1, 2 ]
> a.concat(...b)
[ 1, 2, 3, 4 ]
```

2022-08-03 18:22 UTC, dagvl commented on ticket-storer/index.js
> +const ticketFinder = require('../ticket-collector/src/tickets-finder');
Common code should be factored out of the action and put on a top level so it is clear for the next person modifying the `tickets-finder` action that some other action also uses this code

2022-08-03 18:22 UTC, dagvl commented on ticket-storer/index.js
> +      console.log("Storing overriden repo name", resp);
typo

2022-08-03 18:22 UTC, dagvl commented on ticket-storer/index.js
> +    if (input.overrideRepo != undefined && input.overrideRepo !== "") {
`!=` -> `!==`

2022-08-03 18:22 UTC, dagvl commented on ticket-storer/index.js
> +          console.log(filteredTickets);
I think this is ok here, so we don't overload Jira with concurrent requests, but if you'd want these to run concurrently, you'd store all the Promise objects in an array and use Promise.all(x) on that array.

2022-08-03 18:22 UTC, dagvl commented on ticket-storer/src/dynamodb.js
> +            "ID": { S: `reponame` },
Unneeded templating of static string

2022-08-03 18:22 UTC, dagvl commented on ticket-storer-pr/index.js
> +    if (input.overrideRepo != undefined && input.overrideRepo !== "") {
`!=` -> `!==`

2022-08-04 05:57 UTC, erlend-vimond commented on ticket-storer-pr/action.yml
> +name: 'ticket-collector'
Fixed 👍

2022-08-04 05:57 UTC, erlend-vimond commented on ticket-storer/action.yml
> +description: 'Collects ticket ids'
Fixed 👍

2022-08-04 05:58 UTC, erlend-vimond commented on ticket-storer-pr/index.js
> +    console.log("convertig tickets");
Fixed 👍

2022-08-04 06:03 UTC, erlend-vimond commented on ticket-storer-pr/src/dynamodb.js
> +            "ID": { S: `PR:${prID}` },
Converted everything to use string templating 👍

2022-08-04 06:05 UTC, erlend-vimond commented on ticket-storer/index.js
> +      allTickets = allTickets.concat([...tickets]);
I'm not familiar enough with js to tell, thanks for letting me know! Fixed 👍

2022-08-04 06:06 UTC, erlend-vimond commented on ticket-storer/index.js
> +const ticketFinder = require('../ticket-collector/src/tickets-finder');
Moved the it to a top level "utils" folder, please review.

2022-08-04 06:06 UTC, erlend-vimond commented on ticket-storer/index.js
> +      console.log("Storing overriden repo name", resp);
Fixed 👍

2022-08-04 06:06 UTC, erlend-vimond commented on ticket-storer/index.js
> +    if (input.overrideRepo != undefined && input.overrideRepo !== "") {
Fixed 👍

2022-08-04 06:09 UTC, erlend-vimond commented on ticket-storer/index.js
> +          console.log(filteredTickets);
Doesn't the JIRA search only return one promise? Did you mean the GitHub PR search?

2022-08-04 06:10 UTC, erlend-vimond commented on ticket-storer/src/dynamodb.js
> +            "ID": { S: `reponame` },
Fixed 👍

2022-08-04 06:10 UTC, erlend-vimond commented on ticket-storer-pr/index.js
> +    if (input.overrideRepo != undefined && input.overrideRepo !== "") {
Fixed 👍

2022-08-04 17:11 UTC, dagvl commented on ticket-storer/index.js
> +          console.log(filteredTickets);
I think i was mixing up two pieces of code, i was sure there was a loop here :D Just ignore me...

2022-08-04 17:38 UTC, dagvl approved these changes

2022-08-04 18:36 UTC, merged