Feat/collect list of tickets
vimond/actions pull request #7
Opened 2022-06-15 13:21 UTC by thelo-gaultier

## *What* does this PR do?

This actions collect the tickets matching JIRA's ticket pattern in a Pull request. Specifically we search in:
- The PR title
- The PR description
- All commits message
- If a commit comes from a merge, then we fetch the PR description associated with this merge

## *Why* are you suggesting this change?

So that we can automatically collect the tickets associated with a service upgrade

## *Who* is the change affecting?

At some point the entire company should be more efficient because of this

## JIRA Tickets

PLAT-547

## Manual Testing

Can be tested locally by injecting the following environment variables:
```
GH_TOKEN=<token>
OWNER=vimond
REPO=testing-terraform-management
PR_ID=7
SEARCH_BASE_URL=https://d3sxwm6ufhds2w.cloudfront.net
```

2022-06-16 21:46 UTC, dagvl requested changes
Mostly the package lock urls need to change to not break the build and test workflow in this repo. Alternatively we can setup npm here to use our artifactory?

2022-06-16 21:46 UTC, dagvl commented on ticket-collector/src/tickets-finder.js
> +    findAll: findAllTickets
Style question: Why rename the function in the exports instead of just naming it findAll to begin with?

2022-06-20 07:48 UTC, thelo-gaultier commented on ticket-collector/src/jira.js
> +    })
yes, looking at the documentation it may happen however they are not specific with the rate. There are solutions to get around this:
- Use search instead of Get
- backoff retries 
- short time caching
- only query the new tickets

I ll start with the search API

2022-06-20 20:33 UTC, dagvl reviewed
Looks good to me now. Maybe I found your potential bug, maybe not :D 

On a related note, should we decide on an eslint setup? There are a lot of style issues like inconsistent usage or non-usage of `;` after statements, etc.

2022-06-20 20:33 UTC, dagvl commented on ticket-collector/src/pr-metadata-collector.js
> +    if (searchResponse.data.total_count > 1 ) {
`> 1` seems a bit weird. Do we only do this if we found 2 or more items? (Correct we if that just happens to be how the search response is structured)

2022-06-20 20:33 UTC, dagvl approved these changes

2022-06-20 21:34 UTC, dagvl commented on ticket-collector/index.js
> +    }
@thelo-gaultier I noticed after the review in my code that this pattern is unnecessary. The `core` code already looks for the input in env vars. E.g. for `jira-host` it loads the data from env var named `INPUT_JIRA-HOST`. 

So you can avoid the `process.env.XX || core.getInput("XX")` pattern by just using the above env var names in your .env file instead.

2022-06-20 21:35 UTC, dagvl commented on ticket-collector/index.js
> +    }
e.g. i have
```
    let input = {
      tickets: core.getInput("tickets"),
      inputFile: core.getInput("input-file"),
      prId: core.getInput("pr-id", {required: true}),
      dryRun: core.getBooleanInput("dry-run"),
    }
```
and my .env is 
```
INPUT_TICKETS=W3sia2V5IjoiVEVTVC03ODkiLCJzdW1tYXJ5IjoiTS1UZXN0IHNldCAtIChNb25ldGl6YXRpb24pIC0gVm91Y2hlcnMiLCJsaW5rIjoiaHR0cHM6Ly92aW1vbmQtbmcuYXRsYXNzaWFuLm5ldC9icm93c2UvVEVTVC03ODkifSx7ImtleSI6IlRFU1QtMTIzIiwic3VtbWFyeSI6Ik0tVGVzdCAtIChDYXRhbG9nIC0gQXNzZXRzIC8gUmVsYXRlZCBBc3NldHMpIC0gVmlldyBhc3NldHMgZm9yIGEgU3R1ZGlvL1Nob3ciLCJsaW5rIjoiaHR0cHM6Ly92aW1vbmQtbmcuYXRsYXNzaWFuLm5ldC9icm93c2UvVEVTVC0xMjMifSx7ImtleSI6IlNSLTEyMzQiLCJzdW1tYXJ5IjoiRXJyb3IgRGlzcGxheWluZyB0aGUgY29udGVudCBpbiBWTUFOIHdlYiBicm93c2VyIiwibGluayI6Imh0dHBzOi8vdmltb25kLW5nLmF0bGFzc2lhbi5uZXQvYnJvd3NlL1NSLTEyMzQifSx7ImtleSI6IlBMQVQtMzIxIiwic3VtbWFyeSI6IlVwZ3JhZGUgS2Fma2EgZnJvbSAxLjEuMSB0byAyLjYuMCIsImxpbmsiOiJodHRwczovL3ZpbW9uZC1uZy5hdGxhc3NpYW4ubmV0L2Jyb3dzZS9QTEFULTMyMSJ9LHsia2V5IjoiUExBVC0xMjMiLCJzdW1tYXJ5IjoiaW5ncmVzc2VzLWFwLXNvdXRoZWFzdC0yYS5uY2FiLXByb2QuazhzLnZvcHMuaW8gaW5zdGFuY2UgaXMgcnVubmluZyBvbiBkZWdyYWRlZCBoYXJkd2FyZSwgUmVxdWlyZWQgdG8gc3RvcCBhbmQgc3RhcnQiLCJsaW5rIjoiaHR0cHM6Ly92aW1vbmQtbmcuYXRsYXNzaWFuLm5ldC9icm93c2UvUExBVC0xMjMifV0=
INPUT_PR-ID=4
INPUT_DRY-RUN=false
INPUT_GITHUB_TOKEN=ghp_hahaha

```

2022-06-21 03:16 UTC, dagvl commented on ticket-collector/index.js
> +    }
One more comment .. We should use `core.setSecret(secret)` to hide any accidental secrets that gets logged, e.g.
```
    core.setSecret(input.githubToken);
```

2022-06-21 07:06 UTC, thelo-gaultier commented on ticket-collector/src/pr-metadata-collector.js
> +    if (searchResponse.data.total_count > 1 ) {
Yes, basically the search always returned the current PR. Therefore you only needs to looks for this if we find this commit in more than 1 PRs )

2022-06-21 17:50 UTC, dagvl approved these changes

2022-06-22 18:56 UTC, merged